[*]
wallpaper_mode=stretch
wallpaper=/usr/share/backgrounds/linux95/wallpaper.svg
desktop_bg=#008080
desktop_fg=#ffffff
desktop_shadow=#000000
show_wm_menu=0
sort=mtime;ascending=0
show_documents=0
show_trash=1
show_mounts=0
